In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

Dataset

In [2]:
dataset = pd.read_csv('CAR DETAILS FROM CAR DEKHO.csv')
dataset.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner

In [4]:
dataset.shape

(4340, 8)

In [5]:
dataset.columns

Index(['name', 'year', 'selling_price', 'km_driven', 'fuel', 'seller_type',
       'transmission', 'owner'],
      dtype='object')

In [6]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4340 entries, 0 to 4339
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           4340 non-null   object
 1   year           4340 non-null   int64
 2   selling_price  4340 non-null   int64
 3   km_driven      4340 non-null   int64
 4   fuel           4340 non-null   object
 5   seller_type    4340 non-null   object
 6   transmission   4340 non-null   object
 7   owner          4340 non-null   object
dtypes: int64(3), object(5)
memory usage: 271.4+ KB

Categorical Columns

In [7]:
dataset.select_dtypes(include='object').columns

Index(['name', 'fuel', 'seller_type', 'transmission', 'owner'], dtype='object')

Numerical Columns

In [8]:
dataset.select_dtypes(include=['float64','int64']).columns

Index(['year', 'selling_price', 'km_driven'], dtype='object')

In [9]:
dataset.describe()

              year  selling_price      km_driven
count  4340.000000   4.340000e+03    4340.000000
mean   2013.090783   5.041273e+05   66215.777419
std       4.215344   5.785487e+05   46644.102194
min    1992.000000   2.000000e+04       1.000000
25%    2011.000000   2.087498e+05   35000.000000
50%    2014.000000   3.500000e+05   60000.000000
75%    2016.000000   6.000000e+05   90000.000000
max    2020.000000   8.900000e+06  806599.000000

Any missing values

In [10]:
dataset.isnull().sum()

name             0
year             0
selling_price    0
km_driven        0
fuel             0
seller_type      0
transmission     0
owner            0
dtype: int64

Drop Column

In [12]:
dataset = dataset.drop(columns=['name'])

In [13]:
dataset.head()

,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,2014,450000,141000,Diesel,Individual,Manual,Second Owner

Add column

In [14]:
dataset['Current Year'] = 2026

In [15]:
dataset.head()

,year,selling_price,km_driven,fuel,seller_type,transmission,owner,Current Year
0,2007,60000,70000,Petrol,Individual,Manual,First Owner,2026
1,2007,135000,50000,Petrol,Individual,Manual,First Owner,2026
2,2012,600000,100000,Diesel,Individual,Manual,First Owner,2026
3,2017,250000,46000,Petrol,Individual,Manual,First Owner,2026
4,2014,450000,141000,Diesel,Individual,Manual,Second Owner,2026

How to calculate the car that how many years old it is

In [16]:
dataset['Years Old'] = dataset['Current Year'] - dataset['year']

In [17]:
dataset.head()

,year,selling_price,km_driven,fuel,seller_type,transmission,owner,Current Year,Years Old
0,2007,60000,70000,Petrol,Individual,Manual,First Owner,2026,19
1,2007,135000,50000,Petrol,Individual,Manual,First Owner,2026,19
2,2012,600000,100000,Diesel,Individual,Manual,First Owner,2026,14
3,2017,250000,46000,Petrol,Individual,Manual,First Owner,2026,9
4,2014,450000,141000,Diesel,Individual,Manual,Second Owner,2026,12

In [21]:
dataset = dataset.drop(columns=['Current Year', 'year'], errors='ignore')

In [22]:
dataset.head()

   selling_price  km_driven    fuel seller_type transmission         owner
0          60000      70000  Petrol  Individual       Manual   First Owner
1         135000      50000  Petrol  Individual       Manual   First Owner
2         600000     100000  Diesel  Individual       Manual   First Owner
3         250000      46000  Petrol  Individual       Manual   First Owner
4         450000     141000  Diesel  Individual       Manual  Second Owner

Encoding Categorical variables

In [23]:
dataset.select_dtypes(include='object').columns

Index(['fuel', 'seller_type', 'transmission', 'owner'], dtype='object')

One hot encoding

In [24]:
dataset = pd.get_dummies(data = dataset, drop_first=True)

In [26]:
dataset.head()

,selling_price,km_driven,fuel_Diesel,fuel_Electric,fuel_LPG,fuel_Petrol,seller_type_Individual,seller_type_Trustmark Dealer,transmission_Manual,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,60000,70000,False,False,False,True,True,False,True,False,False,False,False
1,135000,50000,False,False,False,True,True,False,True,False,False,False,False
2,600000,100000,True,False,False,False,True,False,True,False,False,False,False
3,250000,46000,False,False,False,True,True,False,True,False,False,False,False
4,450000,141000,True,False,False,False,True,False,True,False,True,False,False

matrix of feature

In [27]:
x = dataset.drop(columns='selling_price')
y = dataset['selling_price']

In [28]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=0)

In [30]:
x_train.shape

(3038, 12)

In [31]:
x_test.shape

(1302, 12)

Building the Model

In [32]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor()
regressor.fit(x_train, y_train)

RandomForestRegressor()

In [33]:
y_pred = regressor.predict(x_test)

In [34]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.46135783487864357

Hyperparameter tuning

In [35]:
from sklearn.model_selection import RandomizedSearchCV

In [45]:
parameter = {
    'n_estimators': np.arange(100, 1200, 100),
    'criterion': ['squared_error', 'absolute_error'],
    'max_depth': [5, 10, 20,40],
    'min_samples_split': [2, 5, 10, 15, 100],
    'min_samples_leaf': [1, 2, 5, 10],
    'max_features': ['sqrt', 'log2']
}

In [37]:
parameter

{'n_estimators': array([ 100,  200,  300,  400,  500,  600,  700,  800,  900, 1000, 1100]),
 'criterion': ['mse', 'mae'],
 'max_depth': [5, 10, 20, 40],
 'min_samples_split': [2, 5, 10, 15, 100],
 'min_samples_leaf': [1, 2, 5, 10],
 'max_features': ['auto', 'sqrt', 'log2']}

In [46]:
random_cv = RandomizedSearchCV(estimator=regressor, param_distributions=parameter, scoring='neg_mean_squared_error', n_iter=10,
                               cv=5, verbose=2, random_state=0)

In [47]:
random_cv.fit(x_train, y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits
[CV] END criterion=absolute_error, max_depth=20, max_features=sqrt, min_samples_leaf=2, min_samples_split=15, n_estimators=500; total time=  12.5s
[CV] END criterion=absolute_error, max_depth=20, max_features=sqrt, min_samples_leaf=2, min_samples_split=15, n_estimators=500; total time=  11.4s
[CV] END criterion=absolute_error, max_depth=20, max_features=sqrt, min_samples_leaf=2, min_samples_split=15, n_estimators=500; total time=  13.0s
[CV] END criterion=absolute_error, max_depth=20, max_features=sqrt, min_samples_leaf=2, min_samples_split=15, n_estimators=500; total time=  11.5s
[CV] END criterion=absolute_error, max_depth=20, max_features=sqrt, min_samples_leaf=2, min_samples_split=15, n_estimators=500; total time=  11.5s
[CV] END criterion=absolute_error, max_depth=10, max_features=log2, min_samples_leaf=10, min_samples_split=10, n_estimators=100; total time=   1.6s
[CV] END criterion=absolute_error, max_depth=10, max_features=log2, min_samples_leaf=10, min_samples_split=10, n_estimators=100; total time=   1.7s
[CV] END criterion=absolute_error, max_depth=10, max_features=log2, min_samples_leaf=10, min_samples_split=10, n_estimators=100; total time=   1.6s
[CV] END criterion=absolute_error, max_depth=10, max_features=log2, min_samples_leaf=10, min_samples_split=10, n_estimators=100; total time=   1.6s
[CV] END criterion=absolute_error, max_depth=10, max_features=log2, min_samples_leaf=10, min_samples_split=10, n_estimators=100; total time=   1.6s
[CV] END criterion=squared_error, max_depth=40, max_features=log2, min_samples_leaf=5, min_samples_split=2, n_estimators=400; total time=   0.9s
[CV] END criterion=squared_error, max_depth=40, max_features=log2, min_samples_leaf=5, min_samples_split=2, n_estimators=400; total time=   0.9s
[CV] END criterion=squared_error, max_depth=40, max_features=log2, min_samples_leaf=5, min_samples_split=2, n_estimators=400; total time=   1.3s
[CV] END criterion=squared_error, max_depth=40, max_features=log2, min_samples_leaf=5, min_samples_split=2, n_estimators=400; total time=   1.4s
[CV] END criterion=squared_error, max_depth=40, max_features=log2, min_samples_leaf=5, min_samples_split=2, n_estimators=400; total time=   0.9s
[CV] END criterion=absolute_error, max_depth=40, max_features=sqrt, min_samples_leaf=10, min_samples_split=5, n_estimators=900; total time=  15.4s
[CV] END criterion=absolute_error, max_depth=40, max_features=sqrt, min_samples_leaf=10, min_samples_split=5, n_estimators=900; total time=  16.0s
[CV] END criterion=absolute_error, max_depth=40, max_features=sqrt, min_samples_leaf=10, min_samples_split=5, n_estimators=900; total time=  15.4s
[CV] END criterion=absolute_error, max_depth=40, max_features=sqrt, min_samples_leaf=10, min_samples_split=5, n_estimators=900; total time=  16.9s
[CV] END criterion=absolute_error, max_depth=40, max_features=sqrt, min_samples_leaf=10, min_samples_split=5, n_estimators=900; total time=  15.9s
[CV] END criterion=squared_error, max_depth=10, max_features=log2, min_samples_leaf=10, min_samples_split=2, n_estimators=1100; total time=   2.1s
[CV] END criterion=squared_error, max_depth=10, max_features=log2, min_samples_leaf=10, min_samples_split=2, n_estimators=1100; total time=   2.1s
[CV] END criterion=squared_error, max_depth=10, max_features=log2, min_samples_leaf=10, min_samples_split=2, n_estimators=1100; total time=   2.1s
[CV] END criterion=squared_error, max_depth=10, max_features=log2, min_samples_leaf=10, min_samples_split=2, n_estimators=1100; total time=   2.9s
[CV] END criterion=squared_error, max_depth=10, max_features=log2, min_samples_leaf=10, min_samples_split=2, n_estimators=1100; total time=   2.3s
[CV] END criterion=squared_error, max_depth=10, max_features=log2, min_samples_leaf=2, min_samples_split=100, n_estimators=500; total time=   1.0s
[CV] END criterion=squared_error, max_depth=10, max_features=log2, min_samples_leaf=2, min_samples_split=100, n_estimators=500; total time=   1.0s
[CV] END criterion=squared_error, max_depth=10, max_features=log2, min_samples_leaf=2, min_samples_split=100, n_estimators=500; total time=   1.3s
[CV] END criterion=squared_error, max_depth=10, max_features=log2, min_samples_leaf=2, min_samples_split=100, n_estimators=500; total time=   1.0s
[CV] END criterion=squared_error, max_depth=10, max_features=log2, min_samples_leaf=2, min_samples_split=100, n_estimators=500; total time=   1.0s
[CV] END criterion=squared_error, max_depth=40, max_features=log2, min_samples_leaf=10, min_samples_split=10, n_estimators=500; total time=   1.0s
[CV] END criterion=squared_error, max_depth=40, max_features=log2, min_samples_leaf=10, min_samples_split=10, n_estimators=500; total time=   1.0s
[CV] END criterion=squared_error, max_depth=40, max_features=log2, min_samples_leaf=10, min_samples_split=10, n_estimators=500; total time=   1.0s
[CV] END criterion=squared_error, max_depth=40, max_features=log2, min_samples_leaf=10, min_samples_split=10, n_estimators=500; total time=   1.5s
[CV] END criterion=squared_error, max_depth=40, max_features=log2, min_samples_leaf=10, min_samples_split=10, n_estimators=500; total time=   1.5s
[CV] END criterion=absolute_error, max_depth=40, max_features=log2, min_samples_leaf=5, min_samples_split=5, n_estimators=1100; total time=  21.1s
[CV] END criterion=absolute_error, max_depth=40, max_features=log2, min_samples_leaf=5, min_samples_split=5, n_estimators=1100; total time=  22.4s
[CV] END criterion=absolute_error, max_depth=40, max_features=log2, min_samples_leaf=5, min_samples_split=5, n_estimators=1100; total time=  21.7s
[CV] END criterion=absolute_error, max_depth=40, max_features=log2, min_samples_leaf=5, min_samples_split=5, n_estimators=1100; total time=  21.3s
[CV] END criterion=absolute_error, max_depth=40, max_features=log2, min_samples_leaf=5, min_samples_split=5, n_estimators=1100; total time=  22.3s
[CV] END criterion=squared_error, max_depth=20, max_features=sqrt, min_samples_leaf=5, min_samples_split=15, n_estimators=1100; total time=   2.3s
[CV] END criterion=squared_error, max_depth=20, max_features=sqrt, min_samples_leaf=5, min_samples_split=15, n_estimators=1100; total time=   2.7s
[CV] END criterion=squared_error, max_depth=20, max_features=sqrt, min_samples_leaf=5, min_samples_split=15, n_estimators=1100; total time=   3.1s
[CV] END criterion=squared_error, max_depth=20, max_features=sqrt, min_samples_leaf=5, min_samples_split=15, n_estimators=1100; total time=   2.3s
[CV] END criterion=squared_error, max_depth=20, max_features=sqrt, min_samples_leaf=5, min_samples_split=15, n_estimators=1100; total time=   2.3s
[CV] END criterion=squared_error, max_depth=5, max_features=log2, min_samples_leaf=2, min_samples_split=2, n_estimators=300; total time=   0.5s
[CV] END criterion=squared_error, max_depth=5, max_features=log2, min_samples_leaf=2, min_samples_split=2, n_estimators=300; total time=   0.6s
[CV] END criterion=squared_error, max_depth=5, max_features=log2, min_samples_leaf=2, min_samples_split=2, n_estimators=300; total time=   0.5s
[CV] END criterion=squared_error, max_depth=5, max_features=log2, min_samples_leaf=2, min_samples_split=2, n_estimators=300; total time=   0.5s
[CV] END criterion=squared_error, max_depth=5, max_features=log2, min_samples_leaf=2, min_samples_split=2, n_estimators=300; total time=   0.5s

RandomizedSearchCV(cv=5, estimator=RandomForestRegressor(),
                   param_distributions={'criterion': ['squared_error',
                                                      'absolute_error'],
                                        'max_depth': [5, 10, 20, 40],
                                        'max_features': ['sqrt', 'log2'],
                                        'min_samples_leaf': [1, 2, 5, 10],
                                        'min_samples_split': [2, 5, 10, 15,
                                                              100],
                                        'n_estimators': array([ 100,  200,  300,  400,  500,  600,  700,  800,  900, 1000, 1100])},
                   random_state=0, scoring='neg_mean_squared_error', verbose=2)

In [48]:
random_cv.best_params_

{'n_estimators': np.int64(500),
 'min_samples_split': 15,
 'min_samples_leaf': 2,
 'max_features': 'sqrt',
 'max_depth': 20,
 'criterion': 'absolute_error'}

Predicting Single Observation

In [49]:
dataset.head()

,selling_price,km_driven,fuel_Diesel,fuel_Electric,fuel_LPG,fuel_Petrol,seller_type_Individual,seller_type_Trustmark Dealer,transmission_Manual,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,60000,70000,False,False,False,True,True,False,True,False,False,False,False
1,135000,50000,False,False,False,True,True,False,True,False,False,False,False
2,600000,100000,True,False,False,False,True,False,True,False,False,False,False
3,250000,46000,False,False,False,True,True,False,True,False,False,False,False
4,450000,141000,True,False,False,False,True,False,True,False,True,False,False